Add database
SudarikovYaroslav/java-filmorate pull request #10
Opened 2022-06-29 10:44 UTC by SudarikovYaroslav

добавлена диаграмма БД и обновлён README

2022-07-01 07:33 UTC, Arnulogus commented on README.md
> +  ) AS uf_2 ON uf_1.friend_id = uf_2.friend_id;
Сначала мы присоединяем две таблицы, только потом уже используем фильтр where

2022-07-01 07:38 UTC, Arnulogus commented
В целом все здорово, хорошая работа!
Но есть пару замечаний:
1. по поводу статуса дружбы: мне понравилась идея boolean значения, но что если в далеком будущем в нашем приложении появятся новые статусы, то true и false для решения не будет хватать. что если добавить таблицу со статусами?
2. как мне кажется, нет смысла создавать еще одну таблицу genre, а описание добавить в film_genre. но если все же есть желание поделить — думаю, можно добавить в film_genre genre_id, а в genre name (title)

2022-07-01 09:12 UTC, SudarikovYaroslav commented
* По поводу, почему у меня отдельно таблица genre от film_genre:
это потому, что каждому фильму по ТЗ может быть приписано сразу несколько жанров и
свойство "описание жанра" там как-то лишним показалось. Плюс важный момент:
если перенести свойство description в film_genre получится,
что оно никак не будет зависеть от PK film_id, а зависеть будет как раз
от поля genre (описание жанра всё-таки описывает жанр, а не id фильма)
 - а так нельзя. В итоге решил вынести в отдельную таблицу жанры.
* По поводу айдишников в жанрах и рейтингах: я сначала с ними сделал, потом почему-то подумал,
что они там бут лишними, можно и по "имени" сразу связать. Всё же ты прав, наверное
лучше их на место вернуть)) Так в дальнейшем меньше проблем наверное будет.
* Классное замечание по поводу статуса дружбы. Мне нравиться)
В теории можно же ещё добавить статус вроде "лучший друг" или "больше не друг".
Я так и сделаю: отдельный класс со статусами дружбы вместо булевых флажков.

2022-07-01 11:43 UTC, Arnulogus commented
все супер! спасибо за работу

2022-07-10 05:29 UTC, SudarikovYaroslav commented
Хардкорный проект, но вроде всё работает)

2022-07-11 18:53 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getTopFilms(@RequestParam(defaultValue = "10") Integer count) {
"10" можно вынести в константу

2022-07-11 18:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (id < 0 ) throw new FilmNotFoundException("film id:" + id + " не найден");
FilmNotFoundException больше подходит для ситуации, когда по id не найден фильмов в хранилище

в ситуации, когда у фильма отрицательный id, лучше бросать что-то наподобие IllegalStateException

2022-07-11 18:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    @Autowired
аннотация ни к чему не привязана

2022-07-11 18:57 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            throw new UserNotFoundException("id пользователя не может быть отрицательным");
тоже стоит изменить исключение на более подходящее

2022-07-11 19:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FriendLoadingContainer.java
> +public class FriendLoadingContainer {
чтобы не было таких проблем, которые решает этот класс, можно упростить структуру бд:
можно сделать таблицу friendship, где были бы поля userId, friendId, status
где статус - это varchar и его можно мапить в enum джавы

тогда для получения дружбы можно создать класс Friendship, уже из названия которого будет понятно зачем он нужен

2022-07-11 19:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FriendshipStatus.java
> +    private long status_id;
поля в любом случае должны быть в camelCase

2022-07-11 19:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final LikesDao likesDao;
Like для единообразия стоит тоже использовать в единственном числе в названиях

2022-07-11 19:04 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmStorageDao.java
> +public interface FilmStorageDao {
storage и dao - это синонимы, поэтому нужно использовать что-то одно в названии
интерфейс должен называться FilmStorage или FilmDao, а имплементации FilmDaoImpl или например InMemoryFilmDao и DatabaseFilmDao

2022-07-11 19:06 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageDaoImpl.java
> +public class FilmDbStorageDaoImpl implements FilmStorageDao {
в названии стоит поменять порядок слов:
любая реализация интерфейса FilmDao - это ...FilmDao, например InMemorFilmDao

тут подойдет DbFilmDao или DbFilmStorage

2022-07-11 19:08 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaRatingDaoImpl.java
> +                .id(rs.getLong("mpa_rating_id"))
названия полей в таблицах стоит сделать константами класса
это актуально для всех таблиц

2022-07-11 19:14 UTC, makholin requested changes
Нужно исправить замечания

2022-07-12 03:31 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getTopFilms(@RequestParam(defaultValue = "10") Integer count) {
done

2022-07-12 03:50 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (id < 0 ) throw new FilmNotFoundException("film id:" + id + " не найден");
Поскольку по тестам нужно, чтобы результатом на отрицательный id от сервера приходил ответ 404(NOT FOUND)
я сделал отдельный IllegalIdException чтобы в ексепшен хендлере без проблем его можно было отловить и кинуть 
ответ not found, на случай, если в командной разработке придётся где-то  IllegalStateException использовать

done

2022-07-12 03:51 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    @Autowired
done

2022-07-12 03:51 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            throw new UserNotFoundException("id пользователя не может быть отрицательным");
done

2022-07-12 03:53 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/model/FriendshipStatus.java
> +    private long status_id;
done

2022-07-12 03:58 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final LikesDao likesDao;
done

2022-07-12 04:00 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmStorageDao.java
> +public interface FilmStorageDao {
done

2022-07-12 04:00 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageDaoImpl.java
> +public class FilmDbStorageDaoImpl implements FilmStorageDao {
done

2022-07-12 04:42 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaRatingDaoImpl.java
> +                .id(rs.getLong("mpa_rating_id"))
done

2022-07-12 05:35 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/model/FriendLoadingContainer.java
> +public class FriendLoadingContainer {
Нам наставник сказал в этом проекте не использовать Enum-ы, говорил, из-за них тут много сложностей будет. И ещё у нас вся информация: какие есть статусы дружбы, жанры фильмов, рейтинги, должна храниться в БД. поэтому у меня в БД 2 таблицы:
-  userId, friendId, friendship_status_id (хранит id пользователей и id статуса дружбы)
- и отдельно таблица с полями friendship_status_id, status varchar, где храниться какие вообще статусы дружбы есть

Поскольку в ответе нужна мапа пользователей-друзей и статуса (два разных объекта), их придется при таком
раскладе в два отдельных списка загружать двумя разными запросами, а потом как-то собирать в мапу (но тут придётся вообще модель менять т.к. User не имеет поля для статуса дружбы и друзей вообще, всю эту информацию мы перенесли БД). Поэтому я решил объединить обе таблицы с помощью inner join и загрузить всё в промежуточную сущность, которая как-бы сразу два этих объекта сохраняет в себе, а потом очень легко эти данные в мапу раскидать получается. Так выходит за одно обращение к БД всё выгрузить.

Я так понял, что следующий групповой спринт тоже будет по этому проекту, переживаю, что енам будет мешаться
(Владимир Иванов сказал ими не пользоваться, наверное их и не будет ни у кого) Нельзя ли мою реализацию оставить?
Единственное, я подумал, что этот контейнер больше нигде не будет использоваться, поэтому убрал его из модели, и сделал inner class-ом там, где он непосредственно используется (в классе DbUserDaoImpl).

Реализация вроде довольно компактная получилась, можно я так оставлю?

2022-07-12 18:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FriendLoadingContainer.java
> +public class FriendLoadingContainer {
да, можно оставить, я вынес вопрос на обсуждение ревьюеров
пока делайте так, как вам рассказывают, чтобы не было проблем в дальнейших спринтах

2022-07-12 18:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throws IllegalIdException {
рантайм исключения (наследники RuntimeException) не нужно прописывать в сигнатуре

2022-07-12 18:13 UTC, makholin approved these changes
Работа принята

2022-07-13 04:34 UTC, merged