Develop
SudarikovYaroslav/java-filmorate pull request #23
Opened 2022-07-23 05:03 UTC by SudarikovYaroslav

2022-07-23 09:36 UTC, SudarikovYaroslav commented
Только заметил, что последний мерж сделался с иконкой моего личного (не учебного аккаунта git). Не очень понял, как так вышло, но на всякий случай Yarik846 - это тоже я )))

2022-07-24 17:34 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        return new ErrorResponse( "NOT_FOUND",
Нужно добавить форматирование, убрать лишний пробел
аргументы можно оставить на одной строке, как в других хендлерах

2022-07-24 17:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleStorageException(final StorageException e) {
final тут не нужен, стоит убрать, чтобы было одинаково как в других хендлерах

2022-07-24 17:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public static final String DEFAULT_SORT = "year";
можно завести енум с возможными видами сортировки

2022-07-24 17:37 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    public Review add(@Valid @RequestBody Review review) throws StorageException {
StorageException стоит сделать наследником RuntimeException, все равно он нигде не перехватывается и не обрабатывается
а рантайм исключения не надо декларировать у метода

2022-07-24 17:39 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@AllArgsConstructor
аннотации везде стоит выставлять в порядке от самой короткой к самой длинной, так легче читать код

2022-07-24 17:40 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private long eventId;
по названиям полей  не понятно, какой из всех полей с айдишниками отвечает за ид фида?

2022-07-24 17:52 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private long timestamp;
обычно первым полем идет id сущности, которую представляет класс

2022-07-24 17:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return id == film.id;
вам нужно обсудить,  какой для всех классов-моделей будет контракт equal, только по полю id, или по всем полям (например, с помощью аннотации ломбока)

как решите, сделайте для всех классов единообразно

2022-07-24 17:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
у boolean полей не нужна приставка is, она добавляется у геттеров таких полей

2022-07-24 17:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    private void validateDirector(Director director) {
почему не вынести эти методы в отдельный ValidationService?
теперь pojo класс помимо хранения информации еще и отвечает за валидацию этих данных
нарушается принцип Single Responsibility

2022-07-24 17:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        ) throw new InvalidDirectorException("Недопустимы значения поле director");
c if лучше использовать фигурные скобки, даже если выражение только одно
потому иначе это может привести к багам
например:
```
if (true) 
    a();
    b();
```
 
 хотя есть места, где это оправдано, например такие вызовы проверок и сразу возвращение значения
 
 ```
if (a) return 1;
 if (b) return 2;
 if (c) return 3;
```

2022-07-24 18:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        ) throw new InvalidDirectorException("Недопустимы значения поле director");
тут хочется видеть скобки, потому что само условие разбито на несколько строк

2022-07-24 18:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final DbFeedDaoImpl dbFeedDaoImpl;
это поле должно быть типа интерфейса, а не реализации
`private final FeedDao feedDao;`

2022-07-24 18:02 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       LikeDao likeDao, DirectorService directorService, DbFeedDaoImpl dbFeedDaoImpl) {
будет удобнее читать код, если тут каждый аргумент будет на новой строке
а то сейчас первый и второй разделены, а потом все в одну строку

2022-07-24 18:04 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validateNotNull(Film film) {
валидацию стоит вынести в отдельный класс и инжектнуть его в этот сервис и в другие, где это надо
в следующем спринте будет намного легче писать тесты на это и делать моки

2022-07-24 18:05 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +    private void checkId(long id) {
стоит назвать все методы, которые что-то валидируют в одинаковом стиле
validateId(), validateFilmDescriptionLength() и тд

2022-07-24 18:05 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final DbFeedDaoImpl dbFeedDaoImpl;
нужен интерфейс вместо реализации

2022-07-24 18:07 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private int compare(Review p0, Review p1) {
можно Review сделать comparable

2022-07-24 18:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if ((userDao.findUserById(review.getUserId()).isPresent())
если бросается исключение, то блок else if не нужен, код сейчас выглядит очень запутанно
лучше так:
```
if (review.getUserId() == null || review.getFilmId() == null)  throw new IllegalStateException("Не заполнены поля filmId или userId");
if ((userDao.findUserById(review.getUserId()).isEmpty()) throw new StorageException(...);
Review newReview = reviewDao.save(review);
newReview.setUseful(0);
dbFeedDaoImpl.saveFeed(new Feed(Instant.now().toEpochMilli(),
review.getUserId(), "REVIEW", "ADD", 1, review.getReviewId()));
return newReview;
```

2022-07-24 18:12 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new StorageException("Данного отзываc Id = " + id + " нет в БД");
тоже нужно отрефакторить, первым делом в методе сделать проверку и бросить исключение, если нужно, а потом без if else уже выполнять нужную логику

нужно исправить везде, где встречается такая ситуация

2022-07-24 18:13 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
достаточно одной пустой строки

2022-07-24 18:13 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final DbFeedDaoImpl feedDaoImpl;
нужен интерфейс

2022-07-24 18:13 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                userId,"FRIEND","ADD",1,friendId));
нужно отформатировать код
CTRL ALT L в идее

2022-07-24 18:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        feedDaoImpl.saveFeed(new Feed(Instant.now().toEpochMilli(),
фид лучше создать в отдельную переменную сначала, и аргументы конструктора записать в одну строку
сейчас форматирование неправильное

2022-07-24 18:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikeReviewsDao.java
> +    Integer likesNumber(long reviewId);
по названию непонятно, что вернет этот метод
если он возвращает количество лайков у ревью, то лучше назвать `getLikesCount(long reviewId)`

2022-07-24 18:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDao.java
> +    Collection<Review> findReviewsByFilmId (long filmId);
лишний пробел

2022-07-24 18:18 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDao.java
> +    void deleteUserById(Long userId);
аргумент стоит сделать примитивом
1 не будет NPE
2 будет единообразно с остальными методами

2022-07-24 18:19 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbFeedDaoImpl.java
> +                rs.getLong("user_id"),
стоит тоже поля вынести в константы, как например в DbFilmDaoImpl

2022-07-24 18:20 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbReviewDaoImpl.java
> +        return new Review(rs.getLong("review_id"),
строки нужно в константы вынести

2022-07-24 18:22 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeReviewDaoImpl.java
> +                (-1)
-1 нужно вынести в константу и дать ей хоршее имя, сейчас непонятно, почему именно это значение передается

2022-07-24 18:24 UTC, makholin requested changes
Нужно исправить замечания

Еще стоит проверить, что в коде нет варнингов от идеи (оранжевым выделяется), неиспользуемых импортов и код отформатирован.

Отформатировать весь код в файле CTRL ALT L
Удалить неиспользуемые импорты в классе CTL ALT O

2022-07-25 05:10 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private long eventId;
За за ид фида отвечает eventId, мы перенесли его наверх.
Имя eventId, хотели бы оставить, потому, что именно так это поле зовётся во всех тестах в Postman((
Был у нас ещё вариант назвать класс Event вместо Feed, но так наверное тоже путаница начнётся, потому, что тесты для этой функциональности лежат в ветке add-feed, и во всех запросах к контроллеру feed фигурирует.

Если ты не против, мы бы  eventId в качестве имени оставили, чтобы не путаться потом.

2022-07-25 12:08 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
Не понимаю, в чём проблема - при рефакторинге имени с isPositive на Positive отваливается треть всех тестов!
Пробовал вместо аннотаций ломбока прописать вручную геттеры и сеттеры - всёравно начинают падать тесты.
Пока оставил isPositive - как оно есть (((

2022-07-25 12:41 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
Вероятно проблема в том, что в тестах Postman эта переменная называется isPositive.

2022-07-25 13:20 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if ((userDao.findUserById(review.getUserId()).isPresent())
Сделал, малость по-другому, а то так 7 тестов падает.

2022-07-25 13:33 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                userId,"FRIEND","ADD",1,friendId));
done

2022-07-26 17:53 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
ок, без проблем
возможно, такая проблема решится аннотацией, которая задает имя, которое будет поставлено в json для поля класса
но это не критично, можно оставить

2022-07-26 17:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeReviewDaoImpl.java
> +                (LIKE)
скобки не нужны

2022-07-26 17:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikeReviewDaoImpl.java
> +                (DISLIKE)
скобки не нужны

2022-07-26 17:59 UTC, makholin approved these changes
Работа принята

2022-07-26 19:39 UTC, merged