Controllers films users
SudarikovYaroslav/java-filmorate pull request #6
Opened 2022-05-31 07:05 UTC by SudarikovYaroslav

2022-05-31 22:29 UTC, makholin commented on pom.xml
> +			<groupId>com.google.code.gson</groupId>
в спринг буте уже есть нужная зависимость для работы с json

2022-05-31 22:30 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +public abstract class Controller<T> {
для контроллеров обычно не делают абстрактных классов или интерфейсов
обычно они нужны на более низком бизнес слое или слое работы с данными

2022-05-31 22:30 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +@Slf4j
для удобства чтения анотации можно выставить в порядке их длинны от меньшей к большей

2022-05-31 22:32 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Constants.java
> +    public static final String NULL_FILM_FIELDS_LOG = "Объект Film некорректно инициализирован, есть null поля!";
супер, что выносишь в константы значения

но как раз для логов это не нужно делать, потому что они скорее всего не повторяются и в коде проще прочитать сразу сообщение, чем заходить смотреть в константу

2022-05-31 22:33 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film == null) throw new NullPointerException(NULL_FILM_LOG);
NPE лучше не выбрасывать вручную, тут можно выбросить `IllegalStateException`

2022-05-31 22:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new InvalidFilmException(NULL_FILM_FIELDS_LOG);
хорошее решение, правильных подход для валидации, когда на разные проверки бросаются разные исключения и понятно, что упало

2022-05-31 22:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        isNull(user);
isNull предполагает возращение boolean значения
лучше назвать validateNotNull

2022-05-31 22:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +// Не стал использовать @Data от lombok, потому, что наставник и лектор на вебинаре от ЯП сказали, что из-за неё
не попробуешь, не узнаешь))

на самом деле есть два полярных мнения, какие-то команды вообще не используют ломбок и пишут все вручную, кто-то наоборот готов весь бойлерплейт отдать библиотекам

у обоих подходов есть и плюсы и минусы

2022-05-31 22:40 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public long getId() {
лучше попробуй заиспользовать ломбок, в таком проекте навряд ли возникнут проблемы, а ты познакомишься с ним и такого кода гораздо меньше будет

2022-05-31 22:42 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        assertEquals(NULL_FILM_FIELDS_LOG, exNullName.getMessage());
сообщение исключения обычно не проверяют, главное чтобы оно выбрасывалось

2022-05-31 22:42 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        Film blankNameFilm = generateValidFilm();
каждый тест-кейс должен быть в отдельном тесте

2022-05-31 22:45 UTC, makholin commented
Нужно исправить замечания

2022-05-31 22:47 UTC, makholin requested changes
Нужно исправить замечания

2022-06-01 22:33 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Long, Film> films = new HashMap<>();
должна быть private final

2022-06-01 22:34 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            String message = "У фильма отрицательный id";
в сообщения об ошибках стоит добавлять значения, которые ошибочны

`String message = "Invalid film id: " + film.getId();`

2022-06-01 22:37 UTC, makholin requested changes
Все ок, нужно исправить пару замечания

2022-06-02 21:02 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Long, Film> films = new HashMap<>();
поле films должно быть `private final`

2022-06-02 21:03 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final long MAX_FILM_DESCRIPTION_LENGTH = 200L;
а константы как раз можно оставить public, потому что они не изменяются
для них геттеры не нужны

2022-06-02 21:04 UTC, makholin requested changes
у констант private и геттеры не нужны

у films нужно добавить private final

2022-06-03 11:45 UTC, SudarikovYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final long MAX_FILM_DESCRIPTION_LENGTH = 200L;
Поправил)

2022-06-03 21:41 UTC, makholin approved these changes

2022-06-04 06:35 UTC, merged